import { Product, Movement, Category, MovementType } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  // Alimentação
  {
    id: "prod_1",
    name: "Arroz Integral 5kg",
    category: Category.FOOD,
    quantity: 45,
    unit: "sacos",
    unitPrice: 850, // MZN
    minimumStock: 10,
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_2",
    name: "Feijão Preto 1kg",
    category: Category.FOOD,
    quantity: 3,
    unit: "sacos",
    unitPrice: 450,
    minimumStock: 15,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_3",
    name: "Milho Branco 2kg",
    category: Category.FOOD,
    quantity: 28,
    unit: "sacos",
    unitPrice: 320,
    minimumStock: 8,
    lastUpdated: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_4",
    name: "Óleo de Girassol 1L",
    category: Category.FOOD,
    quantity: 156,
    unit: "garrafas",
    unitPrice: 280,
    minimumStock: 20,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_5",
    name: "Sal Fino 1kg",
    category: Category.FOOD,
    quantity: 89,
    unit: "pacotes",
    unitPrice: 95,
    minimumStock: 10,
    lastUpdated: new Date(),
  },
  {
    id: "prod_6",
    name: "Açúcar Refinado 1kg",
    category: Category.FOOD,
    quantity: 2,
    unit: "sacos",
    unitPrice: 180,
    minimumStock: 12,
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_7",
    name: "Farinha de Trigo 1kg",
    category: Category.FOOD,
    quantity: 34,
    unit: "sacos",
    unitPrice: 220,
    minimumStock: 10,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },

  // Bebidas
  {
    id: "prod_8",
    name: "Água Mineral 1.5L",
    category: Category.BEVERAGES,
    quantity: 245,
    unit: "garrafas",
    unitPrice: 85,
    minimumStock: 50,
    lastUpdated: new Date(),
  },
  {
    id: "prod_9",
    name: "Suco Natural Laranja 1L",
    category: Category.BEVERAGES,
    quantity: 78,
    unit: "caixas",
    unitPrice: 150,
    minimumStock: 30,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_10",
    name: "Refrigerante Cola 2L",
    category: Category.BEVERAGES,
    quantity: 1,
    unit: "garrafas",
    unitPrice: 320,
    minimumStock: 15,
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_11",
    name: "Chá Preto Premium 500g",
    category: Category.BEVERAGES,
    quantity: 23,
    unit: "caixas",
    unitPrice: 280,
    minimumStock: 5,
    lastUpdated: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_12",
    name: "Café Moído 500g",
    category: Category.BEVERAGES,
    quantity: 67,
    unit: "pacotes",
    unitPrice: 420,
    minimumStock: 15,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },

  // Limpeza
  {
    id: "prod_13",
    name: "Detergente Neutro 500ml",
    category: Category.CLEANING,
    quantity: 134,
    unit: "garrafas",
    unitPrice: 125,
    minimumStock: 20,
    lastUpdated: new Date(),
  },
  {
    id: "prod_14",
    name: "Alvejante 1L",
    category: Category.CLEANING,
    quantity: 45,
    unit: "garrafas",
    unitPrice: 180,
    minimumStock: 10,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_15",
    name: "Sabão em Pó 1kg",
    category: Category.CLEANING,
    quantity: 0,
    unit: "caixas",
    unitPrice: 320,
    minimumStock: 8,
    lastUpdated: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_16",
    name: "Pano de Limpeza Microfibra",
    category: Category.CLEANING,
    quantity: 456,
    unit: "peças",
    unitPrice: 45,
    minimumStock: 50,
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_17",
    name: "Desinfetante Multisuperfícies 1L",
    category: Category.CLEANING,
    quantity: 78,
    unit: "garrafas",
    unitPrice: 210,
    minimumStock: 15,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },

  // Outros
  {
    id: "prod_18",
    name: "Velas Aromáticas 100g",
    category: Category.OTHER,
    quantity: 234,
    unit: "unidades",
    unitPrice: 85,
    minimumStock: 30,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "prod_19",
    name: "Papel Higiênico Rolo",
    category: Category.OTHER,
    quantity: 567,
    unit: "rolos",
    unitPrice: 35,
    minimumStock: 100,
    lastUpdated: new Date(),
  },
  {
    id: "prod_20",
    name: "Fraldas Tamanho G Pacote",
    category: Category.OTHER,
    quantity: 12,
    unit: "pacotes",
    unitPrice: 850,
    minimumStock: 10,
    lastUpdated: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
];

export const MOCK_MOVEMENTS: Movement[] = [
  // Today's movements
  {
    id: "mov_1",
    productId: "prod_1",
    type: MovementType.EXIT,
    quantity: 5,
    date: new Date(),
    reason: "Venda",
    notes: "Cliente: João Silva",
  },
  {
    id: "mov_2",
    productId: "prod_8",
    type: MovementType.ENTRY,
    quantity: 100,
    date: new Date(),
    reason: "Reposição",
    notes: "Fornecedor: Distribuição ABC",
  },
  {
    id: "mov_3",
    productId: "prod_13",
    type: MovementType.EXIT,
    quantity: 20,
    date: new Date(Date.now() - 2 * 60 * 60 * 1000),
    reason: "Venda",
  },

  // Yesterday's movements
  {
    id: "mov_4",
    productId: "prod_4",
    type: MovementType.EXIT,
    quantity: 10,
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    reason: "Venda",
  },
  {
    id: "mov_5",
    productId: "prod_9",
    type: MovementType.ENTRY,
    quantity: 50,
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    reason: "Reposição",
  },

  // 2 days ago
  {
    id: "mov_6",
    productId: "prod_2",
    type: MovementType.EXIT,
    quantity: 15,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    reason: "Venda",
  },
  {
    id: "mov_7",
    productId: "prod_3",
    type: MovementType.ENTRY,
    quantity: 40,
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    reason: "Reposição",
  },

  // 3 days ago
  {
    id: "mov_8",
    productId: "prod_5",
    type: MovementType.EXIT,
    quantity: 8,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    reason: "Venda",
  },
  {
    id: "mov_9",
    productId: "prod_6",
    type: MovementType.ENTRY,
    quantity: 20,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    reason: "Reposição",
  },

  // 4 days ago
  {
    id: "mov_10",
    productId: "prod_14",
    type: MovementType.EXIT,
    quantity: 5,
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    reason: "Venda",
  },

  // 5 days ago
  {
    id: "mov_11",
    productId: "prod_7",
    type: MovementType.ENTRY,
    quantity: 30,
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    reason: "Reposição",
  },

  // 6 days ago
  {
    id: "mov_12",
    productId: "prod_18",
    type: MovementType.EXIT,
    quantity: 12,
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    reason: "Venda",
  },

  // 7 days ago
  {
    id: "mov_13",
    productId: "prod_19",
    type: MovementType.EXIT,
    quantity: 25,
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    reason: "Venda",
  },
];
